version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./website:/usr/share/nginx/html:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./acme:/acme
    environment:
      - TZ=UTC
    networks:
      - proxy-network
    depends_on:
      - trojan

  trojan:
    image: teddysun/trojan
    container_name: trojan
    restart: always
    volumes:
      - ./trojan/config.json:/etc/trojan/config.json:ro
      - ./ssl:/etc/trojan/ssl:ro
    environment:
      - TZ=UTC
    networks:
      - proxy-network

  acme:
    image: neilpang/acme.sh
    container_name: acme
    restart: always
    volumes:
      - ./acme:/acme
      - ./ssl:/ssl
    environment:
      - TZ=UTC
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    command: daemon

networks:
  proxy-network:
    driver: bridge 