version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "${HTTP_PORT:-80}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./website:/usr/share/nginx/html:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./acme:/acme
    environment:
      - TZ=UTC
    networks:
      - proxy-network

  acme:
    image: neilpang/acme.sh
    container_name: acme
    volumes:
      - ./acme:/acme
      - ./ssl:/ssl
      - ./acme.sh:/acme.sh
    environment:
      - DP_Id=${DP_Id}
      - DP_Key=${DP_Key}
      - TZ=UTC
    networks:
      - proxy-network

  trojan:
    image: trojangfw/trojan
    container_name: trojan
    restart: always
    ports:
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./trojan/config.json.template:/config/config.json.template:ro
      - ./trojan/start-trojan.sh:/start-trojan.sh
      - ./ssl:/ssl:ro
    environment:
      - TZ=UTC
      - TROJAN_PASSWORD=${TROJAN_PASSWORD}
      - TROJAN_REMOTE_ADDR=${TROJAN_REMOTE_ADDR}
      - TROJAN_REMOTE_PORT=${TROJAN_REMOTE_PORT}
    command: sh -c "chmod +x /start-trojan.sh && /start-trojan.sh"
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge 